### ISSUE TITLE
Simple way to download all ads from the vault

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#107]
Just need a simple (one-step) way to do this, doesn't matter how... The goal is to generate a single folder with many thousands of ad images

**Comment by CyrusSUEN** [comment]
On the ad Vault page, press cmd + s and select ```Format: Webpage, Complete```.
After that we can access the saved ```AdNauseam_files folder``` containing mostly the images.

Note that some images are without extension name and some are having .webp which is a Google image format that currently only Opera and Chrome support it.
http://caniuse.com/#feat=webp

**Comment by dhowe** [comment]
Did you try this on Chrome? Mine just hangs...
Also, please create a zip from all the images you have and send to me or post somewhere
