### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#11]
After opening vault:

![screen shot 2016-02-21 at 4 28 36 pm](https://cloud.githubusercontent.com/assets/737638/13201712/3582cbf4-d8b8-11e5-9761-f983e6dd8c2e.png)

**Comment by CyrusSUEN** [comment]
Fixed. Also fixed the same issue on log page
https://github.com/dhowe/AdNauseam2/pull/12
