### ISSUE TITLE
Need custom rule (in default rules) for Yahoo search

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#114]
URL: https://search.yahoo.com/search;_ylt=AobuKuzXeLt1BfpCsufHm7ibvZx4?p=watch&toggle=1&cop=mss&ei=UTF-8&fr=yfp-t-334&fp=1

RENDER:
![screen shot 2016-04-10 at 12 36 19 am](https://cloud.githubusercontent.com/assets/737638/14404895/7c58401e-feb4-11e5-93b2-9268f191e315.png)

**Comment by CyrusSUEN** [comment]
Rules already added: https://github.com/dhowe/AdNauseam2/blob/master/assets/ublock/adnauseam.txt#L6

Can be closed.
