### ISSUE TITLE
Remove jQuery from menu.js (use uDOM instead)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#118]

**Comment by yansh** [comment]
I can attempt this. Though will need to familiarize myself with uDom as I go :D

**Comment by yansh** [comment]
@dhowe I committed my attempt. Seems to work but **appendImageAd** function still uses jquery. I need to figure out how to replace it with ```uDom.append```.

**Comment by yansh** [comment]
Ok, I think I got all of it. I also left the jQuery code in the comments for reference. Let me know if you want me to change anything and create a pull request for it.

Tested on Chrome.

**Comment by dhowe** [comment]
One issue I notice in FF (not sure if its caused by your changes or not):

![screen shot 2016-04-12 at 2 57 34 pm](https://cloud.githubusercontent.com/assets/737638/14452134/149d5ec0-00bf-11e6-819d-bce2b664f058.png)

**Comment by dhowe** [comment]
I've verified this bug in other branches so moving to its own ticket.

**Comment by yansh** [comment]
Cool. I refactored your fix to use uDom on mine.

**Comment by dhowe** [comment]
Great, can you pull the latest changes, make sure everything is still ok, then submit a PR?

**Comment by yansh** [comment]
Sure. Do you want to keep the commented out jQuery code for now?

**Comment by dhowe** [comment]
Great. Might consider doing the same for vault.js (or at least checking whether its possible)... I"ll create a ticket.
