### ISSUE TITLE
Number of ads found in Ad Vault page capped at 400

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam2#120]
![capture](https://cloud.githubusercontent.com/assets/2461812/14409063/748afbca-ff3f-11e5-9ae1-dc984f54fe98.PNG)

In the ADN menu it shows 491 ads found while in the Ad Vault page it shows only 400.

To reproduce, import [this JSON](https://drive.google.com/file/d/0BzHBWuszZv5_RmZkNVc0bmVxYUE/view?usp=sharing) and inspect the Ad Vault page.

**Comment by CyrusSUEN** [comment]
My bad. It is determined by Vault.js::MaxStartNum variable.

**Comment by dhowe** [comment]
And this is only the INITIAL number to start with (so as not to slow loading)... The rest of the ads can be accessed with the date-slider
