### ISSUE TITLE
Menu: should disable 'pause-adnauseam' button on addon pages

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#125]
This should include: options.html, vault.html, chrome://extensions, etc., where this button has no meaning.

![screen shot 2016-04-12 at 3 18 13 pm](https://cloud.githubusercontent.com/assets/737638/14452549/f6e76d32-00c1-11e6-8791-fb360c762ab3.png)

**Comment by rbu** [comment]
What happened to the issue that had this issue number before? How is it that this is now a completely different issue?


![image](https://cloud.githubusercontent.com/assets/65913/15923867/95161f54-2e2f-11e6-8a8e-c898260f8a7e.png)

**Comment by dhowe** [comment]
Issue numbers were reshuffled when we migrated to version 2.x of AdNauseam (which supports Chrome and Opera). You can see the old issue [here](https://github.com/dhowe/AdNauseamV1/issues/125). 

Please give our [beta for chrome](https://github.com/dhowe/AdNauseam/wiki/Installing-AdNauseam) a test !
