### ISSUE TITLE
Bug in vault when ad is selected

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#13]
seems data-width is not getting set correctly on layout...

![screen shot 2016-02-23 at 7 31 23 pm](https://cloud.githubusercontent.com/assets/737638/13250295/1c377ab6-da64-11e5-8d83-e5e2a1d98f2d.png)

**Comment by CyrusSUEN** [comment]
just a typo: https://github.com/dhowe/AdNauseam2/pull/19
