### ISSUE TITLE
Add page title for Ad Vault page

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam2#133]
![vault](https://cloud.githubusercontent.com/assets/2461812/14585105/2fc3e776-049a-11e6-99a7-1cc6dec5a4f1.PNG)
Should have a new locale:
```json
  "adnVaultName": {
    "message": "AdNauseam — Ad Vault",
    "description": "English: AdNauseam — Ad Vault"
  },
```

**Comment by dhowe** [comment]
@cyrus can this be closed?

**Comment by CyrusSUEN** [comment]
> can this be closed?

Yes. After merging this https://github.com/dhowe/AdNauseam2/pull/141
