### ISSUE TITLE
Add tooltip for Pause on Page button

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam2#134]
To do a Pause-on-page: command/alt-click pause-adn in the menu.
![untitled](https://cloud.githubusercontent.com/assets/2461812/14585140/02731506-049c-11e6-8593-2d68d5a1963d.png)

It should have a tooltip like ublock:
![tooltip](https://cloud.githubusercontent.com/assets/2461812/14585130/abdd2178-049b-11e6-960e-b8ab338592b3.png)

**Comment by dhowe** [comment]
Correct. Some of the code is there in menu.js/menu.css/menu.html, but it is not working as yet. See if you can fix.

**Comment by CyrusSUEN** [comment]
Added tooltip: https://github.com/dhowe/AdNauseam2/pull/143
Works on Chrome and Opera. Firefox has no effect. 

The trick is to add a parent container for those HTML elements requiring tooltips. And use CSS ```opacity: 0``` on tooltip to prevent tooltip from showing before calling onShowTooltip(). (Or else the HTML5 'data-tip' attribute will show the tooltip nevertheless)

Question:
1. The tooltip only appears when the Pause button is available. Shall we make it appears whenever the mouse is hovering on top of Pause button?
2. Only Pause button has tooltip because ADN1 doesn't not have tooltip for all the buttons. See: https://github.com/dhowe/AdNauseam/blob/master/locale/en-US.properties#L21-L26
Do shall we add tooltips to other buttons on the Menu?

**Comment by dhowe** [comment]
Is this handling the tooltips in the same way as uBlock does it?

**Comment by dhowe** [comment]
@mushon your input here as to which buttons on menu and settings pages need tooltips would be appreciated

**Comment by CyrusSUEN** [comment]
> is this handling the tooltips in the same way as uBlock does it?

Yes.I've only modified the data tip CSS (of uBlock) to mimic the style in ADN1.

**Comment by dhowe** [comment]
@mushon your input here as to which buttons on menu and settings pages need tooltips would be appreciated

**Comment by CyrusSUEN** [comment]
![untitled](https://cloud.githubusercontent.com/assets/2461812/14765535/a4212722-0a18-11e6-9ca4-5d44bc429af5.png)
This is the current and only tooltip.

**Comment by dhowe** [comment]
Looks good, that one is most important. We can let @mushon decide if we need others...

**Comment by dhowe** [comment]
What is the status on Firefox?

**Comment by CyrusSUEN** [comment]
> status on Firefox

uBlock's approach works on all platforms and I've followed it. Not sure why on Firefox it has no effect. 
I will work debug it once I'm working again.

**Comment by mushon** [comment]
can we separate the enable from the disable texts?
When enabled:
> Click: disable on this site.
> Ctrl+Click: disable only on this page.

When disabled:
> Click: enable on this site.
> Ctrl+Click: enable only on this page.

(might need more precise wording for the disabled mode, to communicate its function)
