### ISSUE TITLE
Text Ad processing broken

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam2#135]
When there are [text ads detected](https://www.google.com.hk/search?q=credit+card&ie=utf-8&oe=utf-8&gws_rd=cr&ei=VxkTV-KuE6G0mwXg6oTABQ) on Firefox,

 1. Vault page cannot be loaded 
 2. Ad Export will be broken

![f1](https://cloud.githubusercontent.com/assets/2461812/14585164/1758689e-049d-11e6-9225-e7d80b67d93a.png)

This is the error msg from the Terminal running jpm command:
```bash
console.warn: Asynchronous operation was aborted as selection changed.
console.error: Downloads:
  Downloads button cannot be found.
```

**Comment by CyrusSUEN** [comment]
I'm at 218fc4bf4a3e5a67233a766097183fbd1885d64e and it seems Google Chrome also has the problem for the text ad detection:
![chrome](https://cloud.githubusercontent.com/assets/2461812/14585464/933049d0-04a9-11e6-8d8b-6c615c283b75.png)
Affected URL: https://www.google.com.hk/search?q=credit+card&oq=credit+card&aqs=chrome..69i57j0l5.1583j0j7&sourceid=chrome&ie=UTF-8

**Comment by dhowe** [comment]
Again, this is a vault problem (see #127), not an addon problem.
