### ISSUE TITLE
Fix menu tooltip on Firefox 

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam2#144]
Currently the menu tooltip only works on Chrome and Opera. 
Need to figure out how to effectively debug Firefox's menu running on jpm and then fix it.

**Comment by yansh** [comment]
How do I get the tooltip to appear in Chrome?

**Comment by dhowe** [comment]
Open the menu on a normal web page (not chrome: or about:) and mouse-over the resume/pause button

**Comment by yansh** [comment]
Strange I tried that and get nothing. 
![apr-26-2016 07-51-06](https://cloud.githubusercontent.com/assets/1371050/14817220/c6931c72-0b83-11e6-8a13-e711283faf6e.gif)

**Comment by dhowe** [comment]
Works for me

![screen shot 2016-04-26 at 7 54 43 pm](https://cloud.githubusercontent.com/assets/737638/14817299/e45c11c2-0be8-11e6-87b6-83deb5718988.png)

**Comment by yansh** [comment]
Got it! Needed to re-build the plug-in. Thanks.

**Comment by yansh** [comment]
BTW It works on Firefox as well.

**Comment by dhowe** [comment]
Please pull again, then add a screenshot of the tooltip in Firefox, then close the ticket.

**Comment by yansh** [comment]
Seems to work on Firefox as well

<img width="456" alt="screen shot 2016-04-26 at 8 14 46 am" src="https://cloud.githubusercontent.com/assets/1371050/14817734/fdbd5282-0b86-11e6-9d8a-ddacb6bd66e3.png">
