### ISSUE TITLE
Text-ad detection

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#150]
Currently both Bing and Ask are not working:

http://www.ask.com/web?q=credit+card&qsrc=0&o=0&l=dir&qo=homepageSearchBox
http://www.bing.com/search?q=watch&go=Submit&qs=n&form=QBRE&pq=watch&sc=8-5&sp=-1&sk=&cvid=70edc762d71a43d88492a479a34f22e3

**Comment by dhowe** [comment]
Bing is done, Ask next.

**Comment by dhowe** [comment]
I don't actually see any text-only ads on Ask

**Comment by CyrusSUEN** [comment]
> I don't actually see any text-only ads on Ask

Do you see any from these results?
http://www.ask.com/web?q=jewelry&qsrc=19&qo=spellCheck&o=0&l=dir
http://www.ask.com/web?q=credit+card&qsrc=1&o=0&l=dir&qo=serpSearchTopBox

**Comment by dhowe** [comment]
No, I only see small ads with images

**Comment by CyrusSUEN** [comment]
After turning off all ad blockers, i see the ads:
![1](https://cloud.githubusercontent.com/assets/2461812/15098056/2844fc1c-1564-11e6-96f2-1208cd1ba782.PNG)

**Comment by dhowe** [comment]
Yes, correct -- these should be handled by ADN.

**Comment by dhowe** [comment]
Check telegram

**Comment by CyrusSUEN** [comment]
Ask and Bing both fixed. Closing this one
