### ISSUE TITLE
Text-ad text overlaps in menu

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#151]
![screen shot 2016-05-05 at 9 32 14 pm](https://cloud.githubusercontent.com/assets/737638/15044722/08db577a-1309-11e6-9743-d79921351aa9.png)

**Comment by CyrusSUEN** [comment]
for more detail, see: https://github.com/dhowe/AdNauseam2/issues/152#issue-153377891

**Comment by dhowe** [comment]
![screen shot 2016-05-12 at 6 16 27 am](https://cloud.githubusercontent.com/assets/737638/15198807/6df1e78e-180c-11e6-8111-951c82ae4142.png)

**Comment by mushon** [comment]
fixed with 029dca9

![uploads/23c233c3-4473-4965-8f40-bcb11d328484/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F23c233c3-4473-4965-8f40-bcb11d328484%2Fblob)
