### ISSUE TITLE
Check that all text-ad filters work the same in Firefox and Opera

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#155]
First test the following text-ad filters in Chrome:
- Yahoo
- Bing
- Google
- Ask

Then test that the results are the same on Firefox and Opera

**Comment by CyrusSUEN** [comment]
On Yahoo and Ask the ads are visible and not getting collected.
Google and Bing works correctly on Chrome.

| Yahoo        |    ads getting hidden        | ads collected  |
| ------------- |:-------------:| -----:|
| Chrome | No| No|
| Opera|No| Yes  |
| Firefox |  Yes|No |

| Google        |    ads getting hidden        | ads collected  |
| ------------- |:-------------:| -----:|
| Chrome |Yes|Yes|
| Opera|Yes| Yes  |
| Firefox |Yes|No|

| Bing        |    ads getting hidden        | ads collected  |
| ------------- |:-------------:| -----:|
| Chrome |Yes|Yes|
| Opera|Yes|Yes |
| Firefox |Yes|No|

| Ask        |    ads getting hidden        | ads collected  |
| ------------- |:-------------:| -----:|
| Chrome | No| No|
| Opera|Partially| No  |
| Firefox |  Partially    |    No |

* Partially means there is a only string "Ads related to: " but without the ads

**Comment by CyrusSUEN** [comment]
Opera 37 comes with a builtin Adblocker that blocks ads on engine level. Luckily this is disabled by default. See: http://www.opera.com/blogs/desktop/2016/05/ad-blocker-opera-for-windows-mac-free/

**Comment by dhowe** [comment]
Please update the chart above after pulling ded48c51fef5, and updating/purging 3rd-party-filters

**Comment by CyrusSUEN** [comment]
> update the chart above after pulling ded48c5

Updated

**Comment by dhowe** [comment]
see #156

**Comment by dhowe** [comment]
And why do I see FF text-ads being collected?

![screen shot 2016-05-09 at 4 56 43 pm](https://cloud.githubusercontent.com/assets/737638/15108176/110be300-1607-11e6-8161-7191ab3b38d1.png)

**Comment by dhowe** [comment]
Bing/FF...

![screen shot 2016-05-09 at 4 56 43 pm](https://cloud.githubusercontent.com/assets/737638/15108504/d7cf751e-1608-11e6-9af3-9880dab09263.png)

**Comment by dhowe** [comment]
Bing/ff

![screen shot 2016-05-09 at 5 10 30 pm](https://cloud.githubusercontent.com/assets/737638/15108531/f76bddfe-1608-11e6-98f0-934451f4e8c8.png)

**Comment by dhowe** [comment]
yahoo/ff

![screen shot 2016-05-09 at 5 11 49 pm](https://cloud.githubusercontent.com/assets/737638/15108559/28b42e02-1609-11e6-8794-7d75cb287f5a.png)

**Comment by dhowe** [comment]
ask/ff

![screen shot 2016-05-09 at 5 12 49 pm](https://cloud.githubusercontent.com/assets/737638/15108585/4abab908-1609-11e6-80dd-9828e0845a7e.png)

**Comment by dhowe** [comment]
@cyrus please update the above table

**Comment by CyrusSUEN** [comment]
Just updated with new browser profiles for each browser. Only 2 problems remain: https://github.com/dhowe/AdNauseam2/issues/153#issuecomment-217821324 https://github.com/dhowe/AdNauseam2/issues/159

This one can be closed.
