### ISSUE TITLE
Text-ads not working in Firefox

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#156]
see #155

**Comment by dhowe** [comment]
Why do I see FF text-ads being collected?

![screen shot 2016-05-09 at 4 56 43 pm](https://cloud.githubusercontent.com/assets/737638/15108176/110be300-1607-11e6-8161-7191ab3b38d1.png)

**Comment by CyrusSUEN** [comment]
> Why do I see FF text-ads being collected?

Was my bad I unchecked "Capture text-only ads whenever possible" in Firefox. After checking that option Firefox has no problem on Google.

Updated the table: https://github.com/dhowe/AdNauseam2/issues/155#issuecomment-217394121
