### ISSUE TITLE
AdNauseam 2.0.1 slows my computer dramatically

### ISSUE THREAD

**Issue by mushon** [dhowe/AdNauseam2#16]
### Describe the issue
Soon after ADN 2.0.1 is installed on Chrome Version 48.0.2564.116 (64-bit) (OSX 10.10.5) it slows down to a level that makes it unusable

I've tried disabling other extensions, it doesn't help.
The browser frees up again as soon as ADN is deactivated.

**Comment by CyrusSUEN** [comment]
I personally don't have this issue on both my Mac and PC.
I think it might be the URL you were visiting or having conflict with other extensions?

**Comment by dhowe** [comment]
I also have not noticed any difference with/without ADN, and I've given the prototype a fair amount of use. Is it possible for you to install it in a brand new install/profile of Chrome (not just with old items disabled)?

**Comment by mushon** [comment]
@dhowe's latest build fixed the problem. Closing.
