### ISSUE TITLE
asset-viewer.html still shows 'uBlock — Asset'

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam2#168]
Should we change it to 'AdNauseam — Asset'?
![capture](https://cloud.githubusercontent.com/assets/2461812/15356049/ec974a54-1d28-11e6-8906-8e45caf186d1.PNG)

**Comment by dhowe** [comment]
Yes

**Comment by CyrusSUEN** [comment]
Fixed: https://github.com/dhowe/AdNauseam2/pull/172
