### ISSUE TITLE
Vault should open in tab, not in new window (FF/Opera)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#22]
Works correctly in Chrome, but not in Firefox or Opera. Appears to be some tricky CSS.

To test, run FF version, click "open advault" or "settings", notice that it opens (incorrectly) in a new window. uBlock has this working correctly for their logger view (see: https://github.com/gorhill/uBlock/blob/master/src/popup.html#L21).

<img width="749" alt="screen shot 2016-02-25 at 4 02 56 pm" src="https://cloud.githubusercontent.com/assets/737638/13313498/64916b52-dbd9-11e5-96e3-58300595ec4a.png">

**Comment by CyrusSUEN** [comment]
on hold

**Comment by dhowe** [comment]
affects both vault and settings on firefox/opera

**Comment by mushon** [comment]
reassigning @dhowe as I think this was accidentally assigned to me. Please reassign to me with more context if my input is needed.

**Comment by dhowe** [comment]
No, this is a CSS issue that we discussed previously, @mushon. We need the advault button, and (other menu buttons in general) to open in new tabs, rather than new windows, across platforms. uBlock appears to accomplish this solely via CSS... however, we have only been able to make it work in Chrome.

**Comment by mushon** [comment]
is it a ``css`` issue or an ``html`` issue? I am not familiar with anything in ``css`` that handles hyperlink functionality and I would be very surprised if such an option exists.

**Comment by dhowe** [comment]
Appears to be css as the HTML is just vanilla <a> link... If you could check how it works in uBlock that would be great... Simply click/inspect the icon pointed to above in FF or Opera...

**Comment by dhowe** [comment]
Problem still apparent on FF/Opera. I notice now that it also doesn't give focus to the vault window when vault is opened subsequently, thus making it appear that the button doesn't work at all. To recreate, open vault, then place vault window behind other windows, then click 'open vault' again.  @mushon or @yansh ?

![screen shot 2016-04-02 at 6 29 55 pm](https://cloud.githubusercontent.com/assets/737638/14225784/823524b0-f901-11e5-8d05-dfd62180b234.png)

**Comment by yansh** [comment]
Ok, adding ```.focus()``` fixes it for Firefox, should also work with Opera. However, if you make the canvas window into a tab it doesn't focus on it when the vault is opened again, but it does refreshes it.

**Comment by dhowe** [comment]
We need it to open as a focused tab, as uBlock does (see above). It should NOT refresh...
It works correctly in Chrome.

**Comment by yansh** [comment]
Yes, it does open a separate window as a tab (as above), however when you add another tab and open the vault again it doesn't put the focus on it. 

Yes, in Chrome it works correctly.

**Comment by yansh** [comment]
Ok, the latest PR should fix it for Firefox, I haven't tested it for Opera. Basically, ```window.open``` has a different behaviour in Firefox. To achieve what we want we need to use the [Tabbed Browser](https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Tabbed_browser) component. I included the snippet from the link and it seems to work.

**Comment by CyrusSUEN** [comment]
OK. Fix verified on all platforms and it work! Thanks @yansh 
But please add one more line before merge the PR. See https://github.com/dhowe/AdNauseam2/pull/110/files#r58771222

**Comment by CyrusSUEN** [comment]
Applied the same fix for Settings page: https://github.com/dhowe/AdNauseam2/pull/111
