### ISSUE TITLE
Change text in addon-manager

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#23]
Should read "Show Adblocker Dashboard", and "Show Adblocker Logger" (not sure if this needs to be changed in Chrome/Opera as well (please check). And description should be changed as well (these changes likely relates to #21). .

![screen shot 2016-02-24 at 8 58 44 pm](https://cloud.githubusercontent.com/assets/737638/13286151/3647dc76-db3a-11e5-8858-326fb99e3af2.png)

**Comment by dhowe** [comment]
Also:
![screen shot 2016-02-24 at 9 45 15 pm](https://cloud.githubusercontent.com/assets/737638/13287081/0fa0d004-db40-11e5-961b-564a15323979.png)

**Comment by CyrusSUEN** [comment]
Fixed. https://github.com/dhowe/AdNauseam2/pull/24. I've only changed the en locale.
Changes affect Chrome, Firefox and Opera just by modifying messages.json.
