### ISSUE TITLE
Badge-updates on tab-switches

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#25]
Need to identify event-handler in ublock for when the activetab changes
Then call uBlock.adnauseam.updateBadge();

**Comment by CyrusSUEN** [comment]
I thought the badge-updates on tab-switches works correctly https://github.com/dhowe/AdNauseam2/issues/14#issuecomment-188697687

Is there a problem?

**Comment by dhowe** [comment]
done
