### ISSUE TITLE
Replace HTML entities in ad displays

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#31]
![screen shot 2016-02-26 at 1 41 33 pm](https://cloud.githubusercontent.com/assets/737638/13344192/cfaeef58-dc8e-11e5-98b4-c46f51ad9dd5.png)

**Comment by CyrusSUEN** [comment]
On what page are we getting this ad?

**Comment by dhowe** [comment]
should be ok now
![screen shot 2016-02-28 at 9 43 28 pm](https://cloud.githubusercontent.com/assets/737638/13379582/5a082602-de64-11e5-8821-336e3646b252.png)
