### ISSUE TITLE
Ad import/export

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#32]
@mushon we need a place for these buttons

**Comment by mushon** [comment]
I think our settings should happen in an Ad Clicking tab. Like this:
![image](https://cloud.githubusercontent.com/assets/27123/13346386/92559a96-dc6e-11e5-9cbb-3e47db91dae1.png)

Then we can adjust the whole settings CSS to fit our design.

This screen shouldn't be a part of our extension:
![image](https://cloud.githubusercontent.com/assets/27123/13346400/a9ca28c2-dc6e-11e5-9e3c-2e6c5367cbe4.png)
I don't think we should go through the uBlock popup at all, it should be folded either into our pop-up or into the settings.
