### ISSUE TITLE
Firefox menu title string not updated

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam2#36]
### Describe the issue
![image](https://cloud.githubusercontent.com/assets/2461812/13362731/f79850be-dd00-11e5-8f44-db6258699da9.png)
Still shows "uBlock Origin" instead of "AdNauseam" before or after the PR: https://github.com/dhowe/AdNauseam2/pull/35

**Comment by dhowe** [comment]
Don't fix for now.
