### ISSUE TITLE
Support legacy format for ad imports (file exported from adn v1.x)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#37]

**Comment by CyrusSUEN** [comment]
Does not work at all at the moment.

**Comment by CyrusSUEN** [comment]
Yes. I was doing a checkup on different functions for #14.

**Comment by dhowe** [comment]
done

**Comment by CyrusSUEN** [comment]
Reopen.

This legacy JSON file from ADN v1.330 cannot be correctly imported.
https://drive.google.com/file/d/0BzHBWuszZv5_TENyZ2lVVG5QUUU/view?usp=sharing

With the following error: 
![capture](https://cloud.githubusercontent.com/assets/2461812/14585070/918ff820-0498-11e6-9926-63378e0c04d3.PNG)

**Comment by dhowe** [comment]
This works fine for me on Chrome. Have you pulled?
Are you testing on Firefox/Opera?

![screen shot 2016-04-17 at 2 34 29 pm](https://cloud.githubusercontent.com/assets/737638/14585467/c194dc3c-04a9-11e6-8ced-13443e5f125b.png)

**Comment by CyrusSUEN** [comment]
Sorry. Uploaded the wrong one.
Mine also works for this JSON (with 2 ads and no Chinese characters)

Please try this one:
https://drive.google.com/file/d/0BzHBWuszZv5_a2s1MWhQcHZYZms/view?usp=sharing

**Comment by dhowe** [comment]
Please don't use Google drive in the future -- just zip the file and drag it into the ticket (or use a gist)

**Comment by CyrusSUEN** [comment]
> just zip the file and drag it into the ticket (or use a gist)

understood

**Comment by dhowe** [comment]
This seems to be a problem in the vault, not with import. Please add the error message to https://github.com/dhowe/AdNauseam2/issues/127 and then see if there is an easy fix. It appears to be calling the width() function on a non-jquery DOM node, for which that function doesn't exist.

**Comment by CyrusSUEN** [comment]
> This seems to be a problem in the vault

I think this ticket could be closed then. 
But let's wait and see if the fix from #127 will fix all these. I verify this ticket again.
