### ISSUE TITLE
Allow selection of directory for ad-export (w' automatically generated filename)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#39]
see your comment in #14

**Comment by CyrusSUEN** [comment]
The <input> HTML tag opens up the 'Open dialog' to select file. But for this case we need a 'Save dialog' (e.g. the dialog when saving an image from the browser). I do not think this operation is possible in Chrome extension. See http://stackoverflow.com/a/11660827
And we've done a similar research on saving the ADN log for porting to Chrome back then. https://github.com/dhowe/AdNauseam-chrome/issues/3

I will stick to uBlock's approach which automatically names the exported file with a date and have it downloaded in the browser's download folder.

Fix: https://github.com/dhowe/AdNauseam2/pull/48
