### ISSUE TITLE
Reset tab counts to 0 after 'clearAds'

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#41]
In this case, the tab still maintains its previous badge count after all ads have been cleared:

![screen shot 2016-02-27 at 3 49 02 pm](https://cloud.githubusercontent.com/assets/737638/13371799/c55605b0-dd69-11e5-8e20-fd519614060b.png)

**Comment by CyrusSUEN** [comment]
This also happens when doing "Delete-Adset (via right-click) in Vault"

**Comment by dhowe** [comment]
These should both be fixed correctly now.
