### ISSUE TITLE
Identify pages with text ads for testing

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#53]
You might be able to find these in an earlier (adn1) ticket.
But we need 5-10 current examples of pages with text-ads (not including google-search)
You can test these with uBlock, by disabling 'cosmetic-filtering' in the uBlock menu.
Once disabled, text-ads should appear.

**Comment by CyrusSUEN** [comment]
Text Ads list:
Yahoo (from Firefox's search bar)
https://search.yahoo.com/yhs/search?p=watch&ei=UTF-8&hspart=mozilla&hsimp=yhs-001
Yahoo US
https://search.yahoo.com/search;_ylt=AobuKuzXeLt1BfpCsufHm7ibvZx4?p=watch&toggle=1&cop=mss&ei=UTF-8&fr=yfp-t-334&fp=1
Bing
http://www.bing.com/search?q=watch&go=Submit&qs=n&form=QBRE&pq=watch&sc=8-5&sp=-1&sk=&cvid=70edc762d71a43d88492a479a34f22e3
DuckDuckGo (only 1 text ad can be found)
https://duckduckgo.com/?q=shopping&t=ffsb&ia=meanings
AOL
http://search.aol.com/aol/search?s_it=topsearchbox.search&s_chn=prt_main5&v_t=comsearch&q=credit+card
Ask
http://www.ask.com/web?q=credit+card&qsrc=0&o=0&l=dir&qo=homepageSearchBox

Disabling 'cosmetic-filtering' has effects on Yahoo, Google, Bing, Duckduckgo and AOL. 
But no effect on Ask.

**Comment by dhowe** [comment]
Now we need to add filters in vault.js to capture these. See the working example for google ads [here](https://github.com/dhowe/AdNauseam2/blob/master/src/js/contentscript-end.js#L128) and the handler function [here](https://github.com/dhowe/AdNauseam2/blob/master/src/js/contentscript-end.js#L262).

You should be able to take much of this code from adn1.

**Comment by CyrusSUEN** [comment]
Added Ask.com detection: https://github.com/dhowe/AdNauseam2/pull/73
But there is a strange problem. Please see https://github.com/dhowe/AdNauseam2/pull/73#discussion_r56755022

**Comment by dhowe** [comment]
Leave this ticket to me.

**Comment by CyrusSUEN** [comment]
Added bing.com detection: https://github.com/dhowe/AdNauseam2/pull/76

Same problem there: https://github.com/dhowe/AdNauseam2/pull/76/files#diff-d0b02e4ded0554ee1d5ee9b80e58b965R282
I can only comment out the code.

Also another problem on bing.com
See 'elem' variable in findAds() in extract.js:
![3](https://cloud.githubusercontent.com/assets/2461812/13906819/2d9225e2-ef1b-11e5-9043-915088ba9aeb.PNG)
That the text ad is detected as img-type ads and the text ad detection is skipped. 
I can only add a workaround like this: https://github.com/dhowe/AdNauseam2/pull/76/files#diff-d0b02e4ded0554ee1d5ee9b80e58b965R33

**Comment by dhowe** [comment]
Closing in favor of #150
