### ISSUE TITLE
 ad entries in the menu not updated after Delete-Adset via right-click

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam2#56]
However if I use the Clear ads button from the settings page the menu is updated (showing empty ad list in the menu)

**Comment by dhowe** [comment]
Confirmed

**Comment by dhowe** [comment]
@CyrusSUEN How is the menu still open when you are clicking on items in the vault?

**Comment by CyrusSUEN** [comment]
When the menu is repoened

**Comment by dhowe** [comment]
Closed. This is fixed, however the badge number still does not update correctly. See #41
