### ISSUE TITLE
deleteAd() broken

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#59]
deleteAd: #1 pre-total: 1
                     post-total: 1

see core.js::420

**Comment by dhowe** [comment]
fixed

**Comment by dhowe** [comment]
waiting on (cross-platform) verification from @CyrusSUEN

**Comment by CyrusSUEN** [comment]
> waiting on (cross-platform) verification from

On Chrome platform
When deleting the ads to 0
![capture](https://cloud.githubusercontent.com/assets/2461812/13889032/6761a498-ed7f-11e5-888b-308aa69693c1.PNG)

**Comment by CyrusSUEN** [comment]
Same problem on Firefox:
![capture](https://cloud.githubusercontent.com/assets/2461812/13889196/2ccb6b92-ed80-11e5-8f19-a9ba216b4773.PNG)

Another problem found is that after deleting the ads to 0, there is no "no ads found" msg and icon in the Vault page unless I resize the browser to trigger the doLayout()

**Comment by dhowe** [comment]
UPDATED: if its the last ad, simply close the vault
Please verify

**Comment by CyrusSUEN** [comment]
> if its the last ad, simply close the vault

The feature works on all platforms. But the old problem persists when reexaminate the inspector:
![capture](https://cloud.githubusercontent.com/assets/2461812/14046137/2b2d4eea-f2da-11e5-87ca-5f5c0cb3aaa7.PNG)

**Comment by CyrusSUEN** [comment]
The number of ads found information (the text at the bottom of the ad Vault page) is inconsistently updated.

The number of ads found was 7 initially which was correct.
After I manually deleted 4 of them it showed 3 which was also correct.
But then once the ad got visited, it changed back to 7 instead of 3:
![1](https://cloud.githubusercontent.com/assets/2461812/14134705/88e9714e-f68b-11e5-9a72-0118d189ac48.png)

**Comment by dhowe** [comment]
Confirmed -- good catch, @CyrusSUEN

**Comment by dhowe** [comment]
fixed, please verify

**Comment by CyrusSUEN** [comment]
Seems ok. But [the old problem mentioned above](https://github.com/dhowe/AdNauseam2/issues/59#issuecomment-201316796) is still there.

But it was buggy at a point that you can see from my screenshot the found ad number was 0 after I deleted some ads. I just cannot reproduce this anymore after 'Clear Ads' and reinstalling the extension.
![123](https://cloud.githubusercontent.com/assets/2461812/14198025/4292c604-f808-11e5-9e8e-4eb97843f1e9.png)

**Comment by dhowe** [comment]
So, the only issue you can recreate now is the console messages?

**Comment by dhowe** [comment]
I've re-nabled the missing the 'no ads found' alert and pushed a fix to the console messages. Please re-verify @CyrusSUEN

**Comment by CyrusSUEN** [comment]
> the only issue you can recreate now is the console messages?

Yes.

> re-nabled the missing the 'no ads found' alert and pushed a fix to the console messages. Please re-verify

Fix verified.

**Comment by dhowe** [comment]
Seems to fail in some cases with imported legacy ads (from old format)

**Comment by dhowe** [comment]
fixed (again)
