### ISSUE TITLE
CSS class progression for discovered ads

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#64]
For vault and menu. Need the correct/standardized progression of css classes (the set of classes for both image and text ads that an item should have) for the following events:

    AdAttempted ->  AdVisited-Success
                              ^
                              |
    AdAttempted -> AdVisited-Failure (#1, #2, #3) -> GiveUp

For example:

    1. Resting: ad-item
    2. On-Attempt: ad-item attempting
    3. On-Success: ad-item attempting just-visited visited
    4. Resting: ad-item visited

Please also check that this is standardized between the vault and menu

**Comment by mushon** [comment]
@dhowe does this need to change from the 1.0 version?

**Comment by dhowe** [comment]
No, but it needs to be a) documented (here), and b) standardized between menu and vault (which is seems it isn't)

**Comment by mushon** [comment]
Attempting:
blue overlay "breathes" on the right margin of the ad
ad frame is blue

Succeed:
purple overlay animates from left to cover the ad and then animates out to the right
ad frame turns purple

Fail:
red overlay animates from left to cover the ad and then animates back to the left
ad frame turns red

The three attempts are not something we need to visualize to the user. It's just a part of our implementation.

The same behavior should function on ads in the vault and on ad items in the menu. It is currently quite standardized in version 1.0

**Comment by dhowe** [comment]
I need to know what the css classes are for each of these...

**Comment by mushon** [comment]
Menu:
``.ad-item.attempting``+``.ad-item-text.attempting``
``.ad-item.just-visited``+``.ad-item-text.just-visited``
``.ad-item.just-failed``+``.ad-item-text.just-failed``

Vault:
``.item.attempting``+``.item-text.attempting``
``.item.just-visited``+``.item-text.just-visited``
``.item.just-failed``+``.item-text.just-failed``

**Comment by dhowe** [comment]
Aren't there are also classes for 'failed' and 'visited'?

And, according to this, no item ever has more than one state, but what about
when an ad has already failed once, and then is being retried? Isn't it both 'failed' and 'attempting'

And are menu.css and vault.css updated to reflect these classes? When I look in menu.css I see classes like '.ad-item.just-visited.failed' and nothing called 'just-failed' ?

**Comment by mushon** [comment]
``.pending`` is set by default for ads that were not visited or failed yet
``.attempting`` is a temporary class that is set on when the visit is attempted and removed when it finishes
``.failed`` (the way I understand it and think makes sense) is only set once the final attempt has failed. In that sense, if we want to try multiple times before giving up we should keep the state as ``.pending`` and switch to ``.atempting`` every time we try it.

the ``.just-visited`` and the ``.just-visited.failed`` classes are temporary and are only used to show the 2  overlay transition that visualize the visit result - purple (success) or red (failure).

This is indeed not implemented the same way in the menu and the vault. How do you prefer me to switch it? Should I go with  ``.just-failed`` or ``.just-visited.failed``?

**Comment by dhowe** [comment]
lets go with how it is in the vault...

to be clear, when an ad fails and shows the red overlay transition, the ad's state is not failed (red outline) unless it is the 3rd try?

**Comment by mushon** [comment]
ok, just pushed b6b0806572be786865d337fdb301ed45075dab54
And yes, the ad should fail only after the final attempt.

**Comment by mushon** [comment]
Reassigning to @dhowe to implement the menu's dynamic class changes in JS

**Comment by dhowe** [comment]
Waiting on #81

**Comment by dhowe** [comment]
@mushon can you document here the final version of what should be happening in terms of both visual appearance and class (just copy/paste from above if already stated). I want to have a firm spec that we can refer to for the future.

**Comment by dhowe** [comment]
@mushon this is still high-priority as Cyrus is trying to close several tickets related to ad states in the vault and menu, but he cannot proceed until without the correct progression of css classes

**Comment by mushon** [comment]
I’ll make sure to attend to this tomorrow. Promise.

**Comment by mushon** [comment]
Static classes
----

``.pending``
- **behavior:** set by default on ads that were not visited or failed yet
- **visual:** frame color is #0076FF blue (as in unvisited link)

``.visited``
- **behavior:** set on ads that were successfully visited
- **visual:** frame color is #A020F0 purple (as in visited link)

``.failed``
- **behavior:** only set once the final attempt has failed.
- **visual:** frame color is #B80606 red (as in empty link)(in Wikipedia)

Please note: on the vault the ``.visited`` class will be set even if the ad was only visited once and even if it has failed every other time it was encountered. Within the focused ad we will see the unique status for every instance of the ad detected. If there are any instances of the ads still ``.attempting`` the stack would be marked as attempting. Only if we've completely given up on visiting this ad stack will we be setting it as ``.failed``.

Temporary classes
----
``.attempting``
- **behavior:** temporary class that is set on when the visit is attempted and removed when it finishes
- **visual:** the :before pseudo-element loop-animates above the left edge of the ad-item

``.just-visited`` 
- **behavior:** temporary class that is set on as soon as the visit is successful
- **visual:** the :before pseudo-element animates purple to cover the ad-item and then continues to slide out from the right edge (when the static class changes to .visited)

``.just-failed`` 
- **behavior:** temporary class that is set on as soon as the visit has failed the very final attempt
- **visual:** the :before pseudo-element animates red to cover the ad-item and then slide back out from from the left edge (when the static class changes to .failed)

**Comment by CyrusSUEN** [comment]
Thank you @mushon for your detailed explanation. The work on  https://github.com/dhowe/AdNauseam2/issues/81 has been done.
Closing this one.
