### ISSUE TITLE
Styling for AdNauseam settings page (dashboard)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#68]
actually this is several related tabs...

![screen shot 2016-03-18 at 6 37 40 pm](https://cloud.githubusercontent.com/assets/737638/13875393/94614ddc-ed38-11e5-9c81-434b671c681b.png)

**Comment by mushon** [comment]
@dhowe please review and merge: 8970732c3c4258df32d3557d5b52d802075f4c60
