### ISSUE TITLE
Safari version broken on gorhill/uBlock

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam2#7]
Even the original gorhill/ublock does not support Safari version. 
I think we should stop developing Adnauseam on Safari.

Steps to build for Safari:
```
$ git checkout c7f1027ab96e72bc60ed63be7d6df4c227ee6713
$ tools/make-safari.sh
```
Load the extension on Safari from ```dist/build/ublock0.safariextension```

**Comment by dhowe** [comment]
Opera is OK ?

**Comment by CyrusSUEN** [comment]
No problem on Opera. After all it is basically the same as Chrome with a different manifest.json.
