### ISSUE TITLE
Need to add default ruleset for AdNauseam

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#72]
For cases where an ad is no longer blocked because its blocking rules have been disabled, we need to add rules to block it cosmetically. 

We have a file for this: assets/users/filters.txt, however its not loading. uBlock appears (at quick read through assets.js) to load lists directly from the repository, perform checksum tests, and do some caching, so not sure where the rules in filters.txt are getting overwritten.

**Comment by yansh** [comment]
How do I recreate this?

**Comment by dhowe** [comment]
There is nothing really to recreate. We want to be able to have a file, with some uBlock rules for ADN, that shows up in the list of rules on the options page (see below). Two test rules you can start with are (from 'assets/user/filters.txt'): 

    yahoo.com##.layoutMiddle
    yahoo.com##.kr5yi684e6

![screen shot 2016-03-31 at 1 46 49 am](https://cloud.githubusercontent.com/assets/737638/14151834/76941de4-f6e2-11e5-8f5b-30801c9b1615.png)

**Comment by yansh** [comment]
Traced the issue to ``` readUserAsset(path, callback)``` -- it looks for the cached content, and returns empty string when not found. 

Replacing ```readUserAsset``` with ```readExternalAsset``` seems to fix the problem, but I have a feeling this is not how the function was intended to be used.

**Comment by dhowe** [comment]
How does this affect the loading and caching of the many other lists (internal and external) that are used?

**Comment by yansh** [comment]
```
  if ( reIsUserPath.test(path) ) {
        readUserAsset(path, callback);
        return;
    }
```
```readUserAsset``` only returns cached content, this is strange because next if statement checks for cached assets.
```
if ( reIsCachePath.test(path) ) {
        readCacheAsset(path, callback);
        return;
    }
```

I probably don't fully understand the all the mechanics behind the code.

**Comment by yansh** [comment]
Ok, from what I see, replacing ``readUserAsset``` with ```readExternalAsset``` works and doesn't seem to effect the loading of other lists. Maybe you guys can double-check. 

In any case, as I mentioned in the above comment, ```readUserAsset``` is really ```readCacheAsset```,  not sure why uBlock chose to have redundant code.

**Comment by yansh** [comment]
Opened an uBlock issue to clarify: https://github.com/gorhill/uBlock/issues/1524#issuecomment-204396735

**Comment by dhowe** [comment]
Great. So looking at the '3rd party filters' in the dashboard, it seems that our case is quite similar to lists #2-6 in the image below, which are stored under 'assets/ublock'. Does it make sense to simply add our list there, perhaps 'assets/ublock/adnauseam.txt', rather than 'assets/user/filters.txt' which seems to be a special case?

![screen shot 2016-04-01 at 9 58 16 pm](https://cloud.githubusercontent.com/assets/737638/14209036/dc7897ac-f854-11e5-9069-324199e27637.png)

**Comment by yansh** [comment]
Frankly I am a bit confused by the subtle difference in these lists.  But I think your suggestion makes sense: "uBlock filters - *" are provided by uBlock, so it makes sense to have a line for "AdNauseam filter filters" provided by AdNauseam. Did I understand it correctly?

**Comment by dhowe** [comment]
Yes. I propose to add our list as the 2nd entry in menu (and in the assets/ublock directory). As follows:
````
My filters
AdNauseam filters
uBlock filters
...
````

**Comment by yansh** [comment]
Cool. From what I see, this requires updating the "checksums.txt" file. There is a bash script for that in the tools folder however since I am running mac, I don't have "truncate" and "md5sum" it requires.

**Comment by dhowe** [comment]
I can give that a run. Do you want to first do a pr for the file updates?

**Comment by dhowe** [comment]
I can give that a try on my mac (I have both)... Do you want to first do a pr for the new file (and remove the user/filters.txt)?

**Comment by yansh** [comment]
Done. Try running the script.

**Comment by dhowe** [comment]
Close for now (thanks to @yansh) -- more testing to come...

**Comment by dhowe** [comment]
!Important
Note that uBlock appears to be in process of redoing their asset management and moving at least a subset of lists to a new external repo: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/
