### ISSUE TITLE
Discuss support for Flattr

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#75]
```
>"I just wanted to add a follow-up on the subject of financing that we talked about earlier. Have you guys 
>ever considered signing AdNauseam up with Flattr, the Sweden-based microdonation site? I can 
>assure you that it is extremely easy to use, both for donators and creators. Based on my own 
>experiences I can recommend it."
>
```

**Comment by mushon** [comment]
@dhowe can you expand on your experience with Flattr?
I am somewhat concerned about throwing money into the mix, especially in the case of this project. If it's not a sum that would substantially change our lives or our ability to sustain the project I would vote against using Flattr or even better suggest donations should go to uBlock or another cause or NGO we would like to tangentially support.

**Comment by dhowe** [comment]
That was not my comment, it was an email message from someone wishing to donate...

**Comment by mushon** [comment]
Oh, ok…
Your thoughts?

**Comment by CyrusSUEN** [comment]
I've just registered a 'Personal account' on https://flattr.com/. 
It's a donation community that supports mainly projects on the Internet.

All accounts on it can both give and receive money in terms of EU currencies.
Once registered an account and setup the payment details you can receive donations.
![2](https://cloud.githubusercontent.com/assets/2461812/13906192/8154f5a2-ef0b-11e5-9938-a8c10aca1199.PNG)

We can also only setup the account on flattr that only takes / receives donations without giving.
![1](https://cloud.githubusercontent.com/assets/2461812/13906193/844d10dc-ef0b-11e5-8763-c2fa68c96492.PNG)

**Comment by CyrusSUEN** [comment]
flattr has 8,130 visitors per day according to https://myip.ms/info/whois/104.27.166.108/k/1958642890/website/flattr.com of which the number is not too low.

However by the means of placing an Flattr button and tell our followers about it we feel like we are a propaganda tool of it. 
And maybe it's my problem I've never heard of it before. Here is its [news collection on TechCrunch](https://www.crunchbase.com/organization/flattr/press)

Not sure if we can get a steady donation per month on Flattr. The only thing I'm sure is that the one emailed @dhowe about it may give at least a one time donation.

I vote against using it at the moment.

**Comment by dhowe** [comment]
On hold for now...
