### ISSUE TITLE
Test animations and item-highlighting for failed visits

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#81]
TO TEST
* Set core.js::testVisitMode to 1
* Collect a bunch of ads
* Open the advault
* Disable internet connection
* Test that animations (red) & state (red after 3 failures) are correct
* Reset core.js::testVisitMode to 0

**Comment by CyrusSUEN** [comment]
Tested only on Chrome.
The behavior is not the same as ADN1.

Now that it visits the current ad twice and then the blue animation goes to the next ad before giving the previous one a red state.

**Comment by dhowe** [comment]
Lets discuss.

**Comment by CyrusSUEN** [comment]
Tested again. 
Here is the screenshot animation:
![2](https://cloud.githubusercontent.com/assets/2461812/14277254/04f7a9fe-fb55-11e5-93db-30fadf3cc8f9.gif)

Not sure if it needs a ".just-visited" animation (it applies a purple color layer) before marking failed ads.
And the failed animation (red status) happened twice.

**Comment by yansh** [comment]
Can you include the ads you tested with?

**Comment by CyrusSUEN** [comment]
Above problems already got fixed by @dhowe.

I've found another problem is that upon a failed visit, the borders of img ads already turn red (should turn red only after 3 failed attempts).
And a fix for this: https://github.com/dhowe/AdNauseam2/pull/130

Please verify
