### ISSUE TITLE
Doesn't detect Google text ads on Firefox

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam2#86]
The text ads shows once ADN is disabled in Firefox's addon page on the same URL such as https://www.google.com.hk/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=credit%20card&oq=credit%20card&aqs=chrome..69i57j69i65l3j0l2.4505j0j7

Works fine on Chrome and Opera.

**Comment by dhowe** [comment]
Please clarify (and/or add a screenshot) -- I don't know what this means.

**Comment by dhowe** [comment]
Fixed
