### ISSUE TITLE
Pages with text-ads that we are not collecting

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#87]
Can we find any more of such pages?

**Comment by yansh** [comment]
Can you elaborate?

**Comment by dhowe** [comment]
So text ads are inline ads that generally require special code to extract their (textual) elements. Rather than showing the image in the ADN menu or vault, we show a placeholder that says 'text-ad'. The classic example are the ads found on Google search. Since these require separate code for each style of ad (stored in the filters array in extract.js), we need to keep track of where they occur (thus this ticket).

![screen shot 2016-04-09 at 12 16 59 pm](https://cloud.githubusercontent.com/assets/737638/14401716/50589ec6-fe4d-11e5-8d82-7e1b4cbdb421.png)

**Comment by dhowe** [comment]
See also https://github.com/dhowe/AdNauseam2/issues/53

**Comment by dhowe** [comment]
Closing in favor of #150
