### ISSUE TITLE
Ads overlapping in vault

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#88]
![screen shot 2016-03-26 at 7 58 00 pm](https://cloud.githubusercontent.com/assets/737638/14059916/40dca1a6-f38d-11e5-9044-86b600668aaa.png)

To recreate the problem, import this set of ads in Chrome:

[AdNauseam-exported-ads_3-26-2016,_7-58-51_PM.json.zip](https://github.com/dhowe/AdNauseam2/files/190470/AdNauseam-exported-ads_3-26-2016._7-58-51_PM.json.zip)

**Comment by yansh** [comment]
Don't seem to overlap for me. Tested in Chrome Version 49.0.2623.87
<img width="697" alt="screen shot 2016-03-27 at 12 54 33 am" src="https://cloud.githubusercontent.com/assets/1371050/14063893/ad118340-f3b6-11e5-90c6-0ac8f7c3970d.png">

**Comment by dhowe** [comment]
May have been a momentary issue with my browser. I'll close this for now and we can reopen if it shows up again... thanks for checking.
