### ISSUE TITLE
Enable click/drag to move all items in the vault

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam2#90]
I believe this was implemented in v1, but not positive (so may be bug)

**Comment by yansh** [comment]
OK, so it seems the drag only works in Firefox, not in Chrome.

**Comment by CyrusSUEN** [comment]
Tried the fix for Chrome from [this](http://stackoverflow.com/a/16579393/1571343)
But it ended up crashing the vault page when dragging which was the reason I removed the dragging attribute in the first place when porting ADN1's UI to ADN2.

**Comment by dhowe** [comment]
low-priority

**Comment by dhowe** [comment]
You need to create a ticket when you remove functionality like this...

**Comment by CyrusSUEN** [comment]
> create a ticket when you remove functionality like this

ok

**Comment by CyrusSUEN** [comment]
Fixed: https://github.com/dhowe/AdNauseam2/pull/173

On Google Chrome simply add the HTML attribute "draggable=true" to #container (even without related dragging JS functions / handlers) will crash the Vault page when dragging.
So I implement it in a new way: use onmousedown and onmouseup event listeners. And this works on all platforms.

**Comment by CyrusSUEN** [comment]
I have another suggestion is that the mouse cursor icon when pressed on the Vault page should be 'move' ![move](https://developer.mozilla.org/@api/deki/files/3443/=move.gif) instead of 'grabbing' ![grabbing](https://developer.mozilla.org/@api/deki/files/3441/=grabbing.gif) to give users more hints that the canvas can be dragged to move.

**Comment by dhowe** [comment]
Sounds good to me

**Comment by CyrusSUEN** [comment]
> Sounds good to me

Updated cursor: https://github.com/dhowe/AdNauseam2/pull/173
