### ISSUE TITLE
Incorrect addon description in Firefox after xpi build

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam2#95]
1. Install adn in Firefox via an xpi (can be created with tools/xpi-build.sh)
2. Click 'More' to show the AdNauseam addon information in Firefox's addon page

![photo_2016-03-29_23-30-28](https://cloud.githubusercontent.com/assets/2461812/14113626/5aa68414-f606-11e5-8bf2-106e66cd17db.jpg)

**Comment by dhowe** [comment]
I recently added tools/xpi-build.sh however it uses jpm which may not be the right way to create an xpi for addons that do not include package.json. Need to figure out the correct way to build an xpi so that the long description is not included (as in the screenshot above).

**Comment by dhowe** [comment]
Ok, so I messed with the build scripts and now I get the correct result in bin/build as an xpi or via run-ff.sh:

![screen shot 2016-03-30 at 12 11 06 am](https://cloud.githubusercontent.com/assets/737638/14115223/b0a372c2-f60c-11e5-8ca0-1b5932b73ac6.png)

**Comment by dhowe** [comment]
Please verify:
1. pull latest changes
2. do $ tools/run-ff.sh
3. check 'more' link in firefox addons page
4. do $ tools/xpi-build.sh
5. drag bin/build/firefox.xpi into Firefox
6. repeat 3.

**Comment by CyrusSUEN** [comment]
Both ways yield the same result as yours:
![2](https://cloud.githubusercontent.com/assets/2461812/14115887/9b1784cc-f60f-11e5-9705-3f372cdc1873.PNG)

Note that the buttons to open uBlock log and Options page have been blank.

**Comment by dhowe** [comment]
These should be coming from platform/firefox/options.xul 
Close this ticket and create a new low-priority bug ticket ticket for the missing labels, assigned to yourself.
Then, if it is easy to fix, do so. If not, leave the ticket open and move on to something with higher priority.

**Comment by dhowe** [comment]
I've fixed this last problem:

![screen shot 2016-03-30 at 2 34 05 pm](https://cloud.githubusercontent.com/assets/737638/14133891/87d3a1ae-f685-11e5-8f11-825e7c18e5f4.png)
